name: 'Expression Service activity generation'
description: 'Generate activities from source code'
inputs:
  query:
    description: 'ETL Query'
    required: true
  count:
    description: 'Number of expressions to extract'
    required: true
  srcDir:
    description: 'Sources directory'
    required: true
  ghToken:
    description: 'GitHub token used to create the issue (e.g. secrets.GITHUB_TOKEN)'
    required: true
#outputs:
#  expressions:
#    description: 'The expressions that were found'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.query }}
    - ${{ inputs.count }}
    - ${{ inputs.srcDir }}
    - ${{ inputs.ghToken }}
